version: '3.7'
services:

  seda-generator:
    networks:
      - internal_services
    container_name: seda-generator
    image: 'registry.libriciel.fr:443/public/plateforme/seda-generator:0.8.1'
    restart: always
    ports:
      - '127.0.0.1:8021:80'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'

  cloudooo:
    networks:
      - internal_services
    container_name: cloudooo
    restart: unless-stopped
    image: 'registry.libriciel.fr/public/actes/cloudooo:7.1.0'
    ports:
      - '127.0.0.1:8011:8011'

  pes-viewer:
    networks:
      - internal_services
    container_name: pes-viewer
    restart: unless-stopped
    image: 'registry.libriciel.fr/public/signature/pes-viewer:1.4.0'
    ports:
      - '127.0.0.1:8888:8888'

  crypto:
    networks:
      - internal_services
    container_name: crypto
    restart: unless-stopped
    image: 'registry.libriciel.fr:443/public/signature/crypto:2.3.1'
    ports:
      - '127.0.0.1:8030:8080'

networks:
  internal_services:
    name: internal_services
